---
- name: 确保 apt keyrings 目录存在
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: 下载微软 VSCode GPG 密钥
  get_url:
    url: https://packages.microsoft.com/keys/microsoft.asc
    dest: /etc/apt/keyrings/packages.microsoft.asc
    mode: '0644'

- name: 添加 VSCode APT 仓库
  apt_repository:
    repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/packages.microsoft.asc] https://packages.microsoft.com/repos/code stable main"
    state: present
    filename: vscode

- name: 安装 VSCode 及依赖
  apt:
    name: 
      - apt-transport-https
      - code
    state: present
    update_cache: yes