---
- include_tasks: apt_apps.yml
  tags: [apps, apt]
- include_tasks: veracrypt.yml
  tags: [apps, veracrypt]
- include_tasks: xnviewmp.yml
  tags: [apps, xnviewmp]
- include_tasks: doublecmd.yml
  tags: [apps, aria2]
- include_tasks: tmm.yml
  tags: [apps, tmm]
- include_tasks: openvpn.yml
  tags: [apps, openvpn]
- include_tasks: thunderbird.yml
  tags: [apps, thunderbird]