[/]
hide-icons=false
hot-sensors=['_memory_usage_', '_system_load_1m_', '__network-rx_max__', '_fan_thinkpad_fan1_', '_temperature_acpi_thermal zone_', '_processor_usage_', '__network-tx_max__']
menu-centered=false
position-in-panel=0
show-battery=false
show-fan=true
show-gpu=false
