---
- name: Apply Netplan
  command: netplan apply

- name: Restart NetworkManager
  service:
    name: NetworkManager
    state: restarted

- name: Reload udev rules
  shell: |
    udevadm control --reload-rules
    udevadm trigger
  # 使用 shell 确保两条命令顺序执行，仅在规则文件发生变化时触发